export const bonusObjectives = [
    "triangle",
    "arm bar",
    "omoplata",
    "guillotine",
    "rear naked choke",
    "darce choke",
    "arm triangle",
    "north-south choke",
    "anaconda",
    "Peruvian necktie",
    "Japanese necktie",
    "gogoplata",
    "Von Flue choke",
    "Monoplata",
    "Americana",
    "Kimura",
    "bicep slicer",
    "wristlock",
    "banana split",
    "electric chair",
    "straight ankle lock",
    "kneebar",
    "calf slicer",
    "toe hold (be VERY careful)",
    "heel hook (be VERY careful)"
  ];